name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Use the value
      run: git clone -b naive https://github.com/klzgrad/forwardproxy
    - name: get xcaddy
      run: go get -u github.com/caddyserver/xcaddy/cmd/xcaddy

    - name: Build
      run: |
        ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=$PWD/forwardproxy --with github.com/caddy-dns/cloudflare
        ls -l      

    - uses: actions/upload-artifact@v2
      with:
        name: caddy_linux_amd64_custom
        path: ./caddy
      
      
